name: onisan
description: "Oni chan package"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter


    #firebase
  cloud_firestore: ^5.4.4 #4.8.0
  firebase_core: ^3.6.0 #2.13.1
  firebase_database: ^11.1.4 #10.2.3
  firebase_auth: ^5.3.1 #4.6.2
  firebase_storage: ^12.3.3 #11.2.2
  firebase_messaging: ^15.1.6 #14.6.7
  firebase_dynamic_links: ^6.0.11
  cloud_functions: ^5.1.5
  firebase_analytics: ^11.3.5
  firebase_app_check: ^0.3.1+6
  firebase_remote_config: ^5.2.0
  #auth
  google_sign_in: ^6.2.2

  #notifs
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0
  badges: ^3.1.2
  easy_search_bar: ^2.5.0

  # image
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  saver_gallery: ^3.0.6
  flutter_svg: ^2.0.10+1
  image_editor_plus: ^1.0.6

  #basics
  connectivity_plus: ^6.1.0
  permission_handler: ^11.3.1
  get: ^4.6.6
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  crypto: ^3.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.1.2

  #text
  auto_size_text: ^3.0.0
  #
  awesome_dialog: ^3.2.1
  percent_indicator: ^4.2.3

  device_info_plus: ^10.1.2

  vibration: ^2.0.0
  pin_code_fields: ^8.0.1
  expandable: ^5.0.1

  flutter_speed_dial: ^7.0.0 # animated btns show

  flutter_xlider: ^3.5.0
  feedback: ^3.1.0

  #
  loading_indicator: ^3.1.1
  url_launcher: ^6.3.0
  flutter_pdfview: ^1.3.4

  flutter_onboarding_slider: ^1.0.11

  #animations
  lottie: ^3.2.0
  rive_animated_icon: ^2.0.2
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  auto_animated: ^3.2.0

  #

  google_maps_flutter: ^2.9.0
  #go_router: ^14.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  #introduction_screen: ^3.1.14
  mime: ^1.0.5
  onboarding: ^4.0.2
  salomon_bottom_bar: ^3.3.2
  video_player: ^2.9.1
  share_plus: ^7.2.2
  dart_openai: ^5.1.0

  smooth_page_indicator: ^1.2.0+3

  font_awesome_flutter: ^10.7.0

  iconsax_plus: ^1.0.0
  easy_stepper: ^0.8.5+1
  pinput: ^5.0.0
  flutter_confetti: ^0.2.0
  confetti: ^0.7.0
  dropdown_button2: ^2.3.9
  multi_select_flutter: ^4.1.3
  syncfusion_flutter_calendar: ^26.2.8
  flutter_colorpicker: ^1.1.0
  calendar_view: ^1.2.0
  thumbnailer: ^2.2.0
  # quill_html_editor: ^2.2.8
  fl_chart: ^0.68.0
  country_code_picker: ^3.0.0
  pull_to_refresh_flutter3: ^2.0.2
  sizer: ^3.0.3
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.1.0
  dio: ^5.6.0
  skeletonizer: ^1.4.2
  #iconsax: ^0.0.8
  icons_plus: ^5.0.0
  stylish_bottom_bar: ^1.1.0
  fluttertoast: ^8.2.8
  bottom_navy_bar: ^6.1.0
  file_selector: ^1.0.3
  file_picker: ^8.1.3
  onesignal_flutter: ^5.2.6
  app_settings: ^5.1.1
  flutter_quill: ^9.3.11
  material_symbols_icons: ^4.2789.0
  flutter_symbols: ^1.0.0
  awesome_bottom_bar: ^1.2.4
  like_button: ^2.0.5
  panara_dialogs: ^0.1.5

  # icon & splash
  flutter_native_splash: ^2.4.1
  #flutter_launcher_icons: "^0.13.1" dev_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
