name: onisan
description: "Oni chan package"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter

  image_cropper: 8.0.2 #BLOCK UPDATE

   #  ^3.8.1 means:  Accept any version >=3.8.1 <4.0.0. so 3.10.0 can be installed

    #firebase: errored
#  firebase_core: ^3.10.0
#
#  cloud_firestore: ^5.6.1
#  firebase_database: ^11.3.0
#  firebase_auth: ^5.4.0
#  firebase_storage: ^12.4.0
#  firebase_messaging: ^15.2.0
#  firebase_dynamic_links: ^6.1.0
#  cloud_functions: ^5.3.0
#  firebase_analytics: ^11.4.0
#  firebase_app_check: ^0.3.2
#  firebase_remote_config: ^5.3.0


  #fb
#  firebase_core: 3.8.1
#  firebase_auth: 5.3.0
#  cloud_firestore: 5.5.1
#  firebase_database: 11.2.0
#  firebase_storage: 12.3.0
#  firebase_messaging: 15.1.6
#  firebase_dynamic_links: 6.0.11
#  cloud_functions: 5.2.0
#  firebase_analytics: 11.3.0
#  firebase_app_check: 0.3.1
#  firebase_remote_config: 5.2.0

    #firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.6
  firebase_dynamic_links: ^6.0.11
  cloud_functions: ^5.1.5
  firebase_analytics: ^11.3.5
  firebase_app_check: ^0.3.1+6
  firebase_remote_config: ^5.2.0
  #auth
  google_sign_in: ^6.2.2

  #notifs
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0
  badges: ^3.1.2

  # image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  saver_gallery: ^4.0.1
  flutter_svg: ^2.0.10+1 #2.0.17 BLOCK
  #image_editor_plus: ^1.0.6

  #basics
  connectivity_plus: ^6.1.0
  permission_handler: ^11.3.1
  get: ^4.6.6
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  crypto: ^3.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.1.2

  #text
  auto_size_text: ^3.0.0
  #
  awesome_dialog: ^3.2.1
  percent_indicator: ^4.2.3

  device_info_plus: ^11.2.1

  pin_code_fields: ^8.0.1
  expandable: ^5.0.1

  flutter_speed_dial: ^7.0.0 # animated btns show

  flutter_xlider: ^3.5.0
  feedback: ^3.1.0

  #
  loading_indicator: ^3.1.1
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.4.0


  #animations
  lottie: ^3.2.0
  rive_animated_icon: ^2.0.2
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  auto_animated: ^3.2.0

  #

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.32
  #go_router: ^14.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  share_plus: ^10.1.4


  country_code_picker: ^3.0.0
  sizer: ^3.0.5



  open_settings_plus: ^0.4.0


  #coach tutor
 # ShowcaseView
#  tutorial_coach_mark
#  Stepper
#  FeatureDiscovery
#  Onboarding
  # icon & splash
  flutter_native_splash: ^2.4.1
  icons_plus: ^5.0.0
  iconsax_plus: ^1.0.0
  font_awesome_flutter: ^10.8.0
  material_design_icons_flutter: ^7.0.7296
  heroicons: ^0.11.0




###############################################################
###############################################################
###############################################################


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
